


mysql:
  dns: "root:wgc970504..@tcp(81.68.120.141:3306)/go_gin_chat?charset=utf8mb4&parseTime=True&loc=Local"


app:
  port: "8322"
  upload_file_path: "e:\\golang\\www\\go-gin-chat\\tmp_images\\"
  cookie_key: "4238uihfieh49r3453kjdfg"
  serve_type: "GoServe"
  debug_mod: "true"


room_auth:
  room_id1:
    user_ids: "1,2"